// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// parse_gff_attributes
DataFrame parse_gff_attributes(CharacterVector gff_attributes, CharacterVector feature_types, CharacterVector annotation_style);
RcppExport SEXP _nexodiff_parse_gff_attributes(SEXP gff_attributesSEXP, SEXP feature_typesSEXP, SEXP annotation_styleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type gff_attributes(gff_attributesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type feature_types(feature_typesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type annotation_style(annotation_styleSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_gff_attributes(gff_attributes, feature_types, annotation_style));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nexodiff_parse_gff_attributes", (DL_FUNC) &_nexodiff_parse_gff_attributes, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_nexodiff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
