# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_gff_attributes <- function(attr_strings, types) {
    .Call('_nexodiff_parse_gff_attributes', PACKAGE = 'nexodiff', attr_strings, types)
}

