# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/nexomis/r-nexoverse:4.4.3-09.25
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Download and decompress kallisto files from Zenodo
        run: |
          mkdir -p tests/testthat/fixtures/integration/ena_datasets/ERX1492351_out
          cd tests/testthat/fixtures/integration/ena_datasets/ERX1492351_out
          wget -O kallisto.tar.gz "https://zenodo.org/records/17061674/files/kallisto.tar.gz?download=1"
          tar -xzf kallisto.tar.gz
          ls -la kallisto/

      - name: Install system dependencies
        run: |
          apt-get update -qq
          apt-get install -y --no-install-recommends \
            wget \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev

      - name: Setup R dependencies
        run: |
          install.packages(c("pkgdown", "devtools", "quarto"))
        shell: Rscript {0}

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
